### PR TITLE
more work completed on markup for all pages

### PR DESCRIPTION
**Pull request by andyaspel**
retrieved deleted branch
aren't I lucky

### CODE REVIEW

**Review by andyaspel — COMMENTED** [review]
good

**Review by andyaspel — COMMENTED** [review]
atlast

**Review by andyaspel — COMMENTED** [review]
good

**Review by andyaspelandyA — APPROVED** [review]
hope it works

**Review by andyaspelandyA — APPROVED** [review]
good

**Review by andyaspelandyA — COMMENTED** [review]
aaaaass

**Review by andyaspelandyA — APPROVED** [review]
aaa

**Review by andyaspelandyA — APPROVED** [review]
aaa

**Review by andyaspelandyA — APPROVED** [review]
ccc

**Review by andyaspelandyA — APPROVED** [review]
ddd

**Review by andyaspelandyA — APPROVED** [review]
dd

**Comment by andyaspel** [comment]
bol

**Pull request closed without merging**
